stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ttran/hadoop-base:hadoop-3.2.0-java8
      pushRemote: true
      registry: gitlab.vigilance.solutions:5005
timeout: 60
branch:
  include:
  - master
